### ISSUE TITLE
Teleport spell briefly travels to location then sends character back to original location

### ISSUE THREAD

**Issue by FrederickEngelhardt** [war3i4i/MagicHeim#1]
Using latest valheim and MagicHeim 1.2.6. When teleporting the character is flung backwards to their original spot. 

Also noting that the documentation website for MagicHeim on Thunderstore is expired. This is the link: https://kg-dev.xyz/

**Comment by war3i4i** [comment]
Fixed. Issue was with new 2022 engine version Rigidbody had some different behaviours compare to 2020
